name: release inference-otel branch

on:
  push:
    branches:
      - inference-otel
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/elasticsearch
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=sha,format=long
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew :distribution:archives:linux-tar:assemble :distribution:archives:linux-aarch64-tar:assemble
      - run: |
          mv distribution/archives/linux-tar distribution/archives/linux-amd64-tar
          mv distribution/archives/linux-aarch64-tar distribution/archives/linux-arm64-tar
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
